### ISSUE TITLE
Is the ATmega32U4-MU chip available?

### ISSUE THREAD

**Issue by SuperRonin** [PrimoriaX/Prozac#1]
I am from China. At present, there is basically no ATmega32U4 chip in the Chinese market. The more popular one is ATmega32U4-MU.

**Comment by PrimoriaX** [comment]
I'm not sure about ATmega32U4-MU, I advise you to search more for a board with ATmega32U4 chip because its guaranteed to work. ( its recommended to get Arduino Leonardo as the code optimized for it)
